spring.application.name=franchise

server.port=8080

# =========================
# R2DBC MYSQL
# =========================
spring.r2dbc.url=r2dbc:mysql://localhost:3306/franchise
spring.r2dbc.username=root
spring.r2dbc.password=123456

# =========================
# LOGS SQL
# =========================
logging.level.org.springframework.r2dbc=DEBUG