spring.application.name=franchise

spring.profiles.active=local

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/franchise_db}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:root}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:root}

spring.sql.init.mode=always